spring:
  application:
    name: Furnish
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.furnish.shop
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
